@startuml diagramaCasoUsoDos
left to right direction
actor "Gerente" as Gerente
actor "Auxiliar Gerencia" as AuxGerencia

rectangle "NeoProv" {
    usecase "Cambiar_Estado_Proveedor" as UC1
    usecase "Actualizar_Proveedor" as UC2
    usecase "Consultar_Proveedor" as UC4
    usecase "Crear_Proveedor" as UC5
}



Gerente --> UC1
Gerente --> UC5
Gerente --> UC4
Gerente --> UC2
AuxGerencia --> UC4



@enduml
